# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-24 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('dogs', 'dogs'), ('cats', 'cats'), ('people', 'people'), ('flowers', 'flowers')], max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('pic_image', models.ImageField(null=True, upload_to='images/')),
                ('image_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('UK', 'UK'), ('RWANDA', 'RWANDA'), ('CANADA', 'CANADA'), ('USA', 'USA')], max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Location'),
        ),
    ]
